---
# tasks file for acme-request/

- name: Private key
  shell: "umask 077 && /usr/bin/openssl genrsa '{{ acme__key_length }}' > '{{ acme__key }}'"
  args:
    creates: '{{ acme__key }}'

- name: Private key permissions
  file:
    path: '{{ acme__key }}'
    owner: 'root'
    group: 'root'
    mode: '0600'

- name: Remove any existing certificate request
  file:
    path: '{{ acme__request }}'
    state: 'absent'

- name: Create a new simple certificate request
  shell: '/usr/bin/openssl req -new -sha256 -key {{ acme__key }} -subj "/CN={{ acme__domain }}" > {{ acme__request }}'
  args:
    creates: '{{ acme__request }}'
  when: acme__domain is string

- name: Create a new multi-domain certificate request
  shell: '/usr/bin/openssl req -new -sha256 -key {{ acme__key }} -subj "/" -reqexts SAN -config <(cat {{ acme__openssl_config }} <(printf "[SAN]\nsubjectAltName=DNS:{{ acme__domain | join(",DNS:") }}")) > {{ acme__request }}'
  args:
    executable: '/bin/bash'
    creates: '{{ acme__request }}'
  when: acme__domain is iterable and not acme__domain is string
  failed_when: False

